bookeep/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.get_name, name='home'),
    path('post/', views.post_data, name='post'),
    path('update/<id>', views.update, name='update'),
]

curd/urls.py
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bookeep.urls')),
    path('admin/', admin.site.urls),
]

bookeep/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.first_name

bookeep/forms.py
from django.forms import ModelForm
from bookeep.models import Person


class PersonForm(ModelForm):
     class Meta:
         model = Person
         fields = ['first_name', 'last_name']

bookeep/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import PersonForm
from .models import Person
from django.shortcuts import redirect
from django.urls import reverse




# Create your views here.
def index(request):

    return HttpResponse("Hello, world. You're at the polls index.")


def get_name(request):
    all = Person.objects.all()
    # all.delete()
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = PersonForm()

    return render(request, 'bookeep/index.html', {'form': form, "all": all})

def update(request, id):
    all = Person.objects.all()
    if request.method == 'POST':
        instance = Person.objects.get(id=id)
        form = PersonForm(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')

    else:
        instance = Person.objects.get(id=id)
        form = PersonForm(instance=instance)
        return render(request, 'bookeep/index.html', {'form': form, "all": all})


def post_data(request):

    if request.method == 'POST':
        if request.POST["operation"] == "Delete" and request.POST.get("item") != None:
            obj = Person.objects.get(id=request.POST["item"])
            obj.delete()
            return HttpResponseRedirect('/')
        elif request.POST["operation"] == "Update" and request.POST.get("item") != None:
            return redirect(reverse('update', kwargs={'id': request.POST["item"]}))

        else:
            return HttpResponseRedirect('/')

    else:
        return HttpResponseRedirect('/')

bookeep/templates/bookeep/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <title>Django CURD</title>
  </head>
  <body>
   <div class="container my-2">
    <h1 class="text-center text-danger">Crud App <i class="bi bi-emoji-sunglasses"></i></h1>
    <hr class="mb-4">
    <div class="row mb-3">
      <div class="col-md-8 col-sm-12 mx-auto">
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <div class="row">
              <div class="col-md-6">
                <label for="id_first_name">First Name</label>
                {{ form.first_name}}
              </div>
              <div class="col-md-6">
                <label for="id_last_name">Last Name</label>
                {{form.last_name}}
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Submit <i class="bi bi-check-circle-fill"></i></button>
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-sm-12 mx-auto">
        <form method="post" action="{% url 'post' %}">
          {% csrf_token %}

          <table class="table">
              <thead class="thead-dark">
                  <tr >
                      <th>Sr.No</th>
                      <th>First</th>
                      <th>Last</th>
                      <th>Select</th>
                  </tr>
              </thead>
              {% for a in all %}
              <tr>
                  <td>{{ a.id }}</td>
                  <td>{{ a.first_name }}</td>
                  <td>{{ a.last_name }}</td>
                  <td><input type='radio' name="item" value="{{a.id}}"></td>
              </tr>
              {% endfor %}
          </table>
          <hr>
          <div class="d-flex justify-content-center">
            <input type="submit"  class="btn btn-danger mr-2" name = "operation" value="Delete">
            <input type="submit" class="btn btn-primary" name = "operation" value="Update">
          </div>
        </form>
      </div>
    </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      // for styling adding classes
      document.getElementById('id_first_name').classList.add('form-control')
      document.getElementById('id_last_name').classList.add('form-control')
    </script>
  </body>
</html>